export const COLUMN_LABELS_RU = {
  fullName: "ФИО",
  pin: "PIN",
  documentNumber: "Номер документа",
  declaredAddress: "Декларированный адрес",
  residentialAddress: "Фактический адрес",
  bank: "Банк",
  swift: "SWIFT",
  iban: "IBAN",
  phoneNumber: "Телефон",
  email: "E-mail",
  carId: "Машина",
  status: "Статус",
  agreementNumber: "Номер договора",
  signingDate: "Дата заключения",
  expirationDate: "Дата окончания",
  agreementDuration: "Срок (мес.)",
  paymentDate: "Дата платежа",
  lastPaymentDate: "Последний платёж",
  companyName: "Имя компании",
  registrationNo: "Регистрационный номер",
  legalAddress: "Юридический адрес",
  representedBy: "Представитель",
  leaseRate: "Ставка (%)",
  downPayment: "Первый взнос (%)",
  downPaymentAmount: "Взнос (EUR)",
  monthlyPayment: "Платёж",
  preparationFee: "Сбор",
  totalAmount: "Общая сумма",
  paidAmount: "Оплачено",
  debtRemaining: "Остаток",
  makeModel: "Марка и модель",
  yearOfManufacture: "Год выпуска",
  vin: "VIN",
  plate: "Гос. номер",
  mileage: "Пробег",
  cost: "Цена (EUR)",
};

export const SENSITIVE_FIELDS = ["vin", "pin", "iban", "swift"];